name: Scheduled production API warm-up

on:
  schedule:
    - cron: "*/5 * * * *" ## Every 5 minutes

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  warm_up_production_api:
    name: Warm up production API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: ## Checkout the branch that triggered the workflow
          ref: ${{ github.ref }}

      - uses: ./.github/actions/warm-up-vercel
        with:
          deployment-base-url: "https://project-vayua-platform-git-platform-102-dreamqip.vercel.app"
